name: AssetStudioBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # 不使用 microsoft/setup-msbuild action，而是直接在 Windows 环境中查找 MSBuild
      - name: Setup MSBuild Path
        shell: powershell
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          if ($vsPath) {
            Write-Host "Found MSBuild at: $vsPath"
            echo "MSBUILD_PATH=$vsPath" >> $env:GITHUB_ENV
            # 将 MSBuild 目录添加到 PATH
            $msbuildDir = Split-Path -Parent $vsPath
            echo "$msbuildDir" >> $env:GITHUB_PATH
          } else {
            Write-Error "MSBuild not found!"
            exit 1
          }
      
      - name: Download FBX SDK
        run: |
          md fbx
          cd fbx
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe" -OutFile "fbxsdk.exe"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_pdbs.exe" -OutFile "fbxpdb.exe"
          Start-Process -FilePath "fbxpdb.exe" /S -Wait
          cd ..

      - name: Nuget Restore
        run: nuget restore
      
      - name: Build .Net472
        run: msbuild /p:Configuration=Release /p:TargetFramework=net472 /verbosity:minimal

      - name: Build .Net5
        run: msbuild /t:AssetStudioGUI:publish /p:Configuration=Release /p:TargetFramework=net5.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Build .Net6
        run: msbuild /t:AssetStudioGUI:publish /p:Configuration=Release /p:TargetFramework=net6.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Upload .Net472 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssetStudio.net472
          path: AssetStudioGUI/bin/Release/net472

      - name: Upload .Net5 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssetStudio.net5
          path: AssetStudioGUI/bin/Release/net5.0-windows/publish

      - name: Upload .Net6 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AssetStudio.net6
          path: AssetStudioGUI/bin/Release/net6.0-windows/publish
