name: AssetStudioBuildManual

on:
  # 只保留手动触发
  workflow_dispatch:
    # 可以添加一些输入选项，让手动触发更灵活
    inputs:
      buildNet472:
        description: 'Build .Net472'
        required: true
        default: 'true'
      buildNet5:
        description: 'Build .Net5'
        required: true
        default: 'true'
      buildNet6:
        description: 'Build .Net6'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # 使用更新版本的 setup-msbuild 并添加重试机制
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '[17.0,18.0)'
        continue-on-error: false
        timeout-minutes: 5
      
      - name: Download FBX SDK
        run: |
          md fbx
          cd fbx
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe" -OutFile "fbxsdk.exe"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_pdbs.exe" -OutFile "fbxpdb.exe"
          Start-Process -FilePath "fbxpdb.exe" /S -Wait
          cd ..
        timeout-minutes: 15

      - name: Nuget Restore
        run: nuget restore
        timeout-minutes: 10
      
      - name: Build .Net472
        if: ${{ github.event.inputs.buildNet472 == 'true' }}
        run: msbuild /p:Configuration=Release /p:TargetFramework=net472 /verbosity:minimal
        timeout-minutes: 15

      - name: Build .Net5
        if: ${{ github.event.inputs.buildNet5 == 'true' }}
        run: msbuild /t:AssetStudioGUI:publish /p:Configuration=Release /p:TargetFramework=net5.0-windows /p:SelfContained=false /verbosity:minimal
        timeout-minutes: 15

      - name: Build .Net6
        if: ${{ github.event.inputs.buildNet6 == 'true' }}
        run: msbuild /t:AssetStudioGUI:publish /p:Configuration=Release /p:TargetFramework=net6.0-windows /p:SelfContained=false /verbosity:minimal
        timeout-minutes: 15

      - name: Upload .Net472 Artifact
        if: ${{ github.event.inputs.buildNet472 == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: AssetStudio.net472
          path: AssetStudioGUI/bin/Release/net472
          retention-days: 30

      - name: Upload .Net5 Artifact
        if: ${{ github.event.inputs.buildNet5 == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: AssetStudio.net5
          path: AssetStudioGUI/bin/Release/net5.0-windows/publish
          retention-days: 30

      - name: Upload .Net6 Artifact
        if: ${{ github.event.inputs.buildNet6 == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: AssetStudio.net6
          path: AssetStudioGUI/bin/Release/net6.0-windows/publish
          retention-days: 30
